(cl:defpackage ur10_robot_arm-srv
  (:use )
  (:export
   "ENDEFFECTORPOSE"
   "<ENDEFFECTORPOSE-REQUEST>"
   "ENDEFFECTORPOSE-REQUEST"
   "<ENDEFFECTORPOSE-RESPONSE>"
   "ENDEFFECTORPOSE-RESPONSE"
   "FRAMEDEV"
   "<FRAMEDEV-REQUEST>"
   "FRAMEDEV-REQUEST"
   "<FRAMEDEV-RESPONSE>"
   "FRAMEDEV-RESPONSE"
  ))

