// Generated by gencpp from file ur10_robot_arm/endEffectorPose.msg
// DO NOT EDIT!


#ifndef UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSE_H
#define UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSE_H

#include <ros/service_traits.h>


#include <ur10_robot_arm/endEffectorPoseRequest.h>
#include <ur10_robot_arm/endEffectorPoseResponse.h>


namespace ur10_robot_arm
{

struct endEffectorPose
{

typedef endEffectorPoseRequest Request;
typedef endEffectorPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct endEffectorPose
} // namespace ur10_robot_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_robot_arm::endEffectorPose > {
  static const char* value()
  {
    return "ab49f52154a9a8f037faf1e645e24d47";
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPose&) { return value(); }
};

template<>
struct DataType< ::ur10_robot_arm::endEffectorPose > {
  static const char* value()
  {
    return "ur10_robot_arm/endEffectorPose";
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPose&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_robot_arm::endEffectorPoseRequest> should match
// service_traits::MD5Sum< ::ur10_robot_arm::endEffectorPose >
template<>
struct MD5Sum< ::ur10_robot_arm::endEffectorPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_robot_arm::endEffectorPose >::value();
  }
  static const char* value(const ::ur10_robot_arm::endEffectorPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_robot_arm::endEffectorPoseRequest> should match
// service_traits::DataType< ::ur10_robot_arm::endEffectorPose >
template<>
struct DataType< ::ur10_robot_arm::endEffectorPoseRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_robot_arm::endEffectorPose >::value();
  }
  static const char* value(const ::ur10_robot_arm::endEffectorPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_robot_arm::endEffectorPoseResponse> should match
// service_traits::MD5Sum< ::ur10_robot_arm::endEffectorPose >
template<>
struct MD5Sum< ::ur10_robot_arm::endEffectorPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_robot_arm::endEffectorPose >::value();
  }
  static const char* value(const ::ur10_robot_arm::endEffectorPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_robot_arm::endEffectorPoseResponse> should match
// service_traits::DataType< ::ur10_robot_arm::endEffectorPose >
template<>
struct DataType< ::ur10_robot_arm::endEffectorPoseResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_robot_arm::endEffectorPose >::value();
  }
  static const char* value(const ::ur10_robot_arm::endEffectorPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSE_H
