// Generated by gencpp from file ur10_robot_arm/frameDev.msg
// DO NOT EDIT!


#ifndef UR10_ROBOT_ARM_MESSAGE_FRAMEDEV_H
#define UR10_ROBOT_ARM_MESSAGE_FRAMEDEV_H

#include <ros/service_traits.h>


#include <ur10_robot_arm/frameDevRequest.h>
#include <ur10_robot_arm/frameDevResponse.h>


namespace ur10_robot_arm
{

struct frameDev
{

typedef frameDevRequest Request;
typedef frameDevResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct frameDev
} // namespace ur10_robot_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur10_robot_arm::frameDev > {
  static const char* value()
  {
    return "a3a39a6de41cd121631db316fe36d1b6";
  }

  static const char* value(const ::ur10_robot_arm::frameDev&) { return value(); }
};

template<>
struct DataType< ::ur10_robot_arm::frameDev > {
  static const char* value()
  {
    return "ur10_robot_arm/frameDev";
  }

  static const char* value(const ::ur10_robot_arm::frameDev&) { return value(); }
};


// service_traits::MD5Sum< ::ur10_robot_arm::frameDevRequest> should match
// service_traits::MD5Sum< ::ur10_robot_arm::frameDev >
template<>
struct MD5Sum< ::ur10_robot_arm::frameDevRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_robot_arm::frameDev >::value();
  }
  static const char* value(const ::ur10_robot_arm::frameDevRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_robot_arm::frameDevRequest> should match
// service_traits::DataType< ::ur10_robot_arm::frameDev >
template<>
struct DataType< ::ur10_robot_arm::frameDevRequest>
{
  static const char* value()
  {
    return DataType< ::ur10_robot_arm::frameDev >::value();
  }
  static const char* value(const ::ur10_robot_arm::frameDevRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur10_robot_arm::frameDevResponse> should match
// service_traits::MD5Sum< ::ur10_robot_arm::frameDev >
template<>
struct MD5Sum< ::ur10_robot_arm::frameDevResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur10_robot_arm::frameDev >::value();
  }
  static const char* value(const ::ur10_robot_arm::frameDevResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur10_robot_arm::frameDevResponse> should match
// service_traits::DataType< ::ur10_robot_arm::frameDev >
template<>
struct DataType< ::ur10_robot_arm::frameDevResponse>
{
  static const char* value()
  {
    return DataType< ::ur10_robot_arm::frameDev >::value();
  }
  static const char* value(const ::ur10_robot_arm::frameDevResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR10_ROBOT_ARM_MESSAGE_FRAMEDEV_H
