// Generated by gencpp from file ur10_robot_arm/endEffectorPoseRequest.msg
// DO NOT EDIT!


#ifndef UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSEREQUEST_H
#define UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur10_robot_arm
{
template <class ContainerAllocator>
struct endEffectorPoseRequest_
{
  typedef endEffectorPoseRequest_<ContainerAllocator> Type;

  endEffectorPoseRequest_()
    : checkPose(false)  {
    }
  endEffectorPoseRequest_(const ContainerAllocator& _alloc)
    : checkPose(false)  {
  (void)_alloc;
    }



   typedef uint8_t _checkPose_type;
  _checkPose_type checkPose;





  typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct endEffectorPoseRequest_

typedef ::ur10_robot_arm::endEffectorPoseRequest_<std::allocator<void> > endEffectorPoseRequest;

typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseRequest > endEffectorPoseRequestPtr;
typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseRequest const> endEffectorPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.checkPose == rhs.checkPose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_robot_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3073ea84b3861f7782ffb85197bf3493";
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3073ea84b3861f77ULL;
  static const uint64_t static_value2 = 0x82ffb85197bf3493ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_robot_arm/endEffectorPoseRequest";
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool checkPose\n"
;
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.checkPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct endEffectorPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_robot_arm::endEffectorPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "checkPose: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.checkPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSEREQUEST_H
