// Generated by gencpp from file ur10_robot_arm/endEffectorPoseResponse.msg
// DO NOT EDIT!


#ifndef UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSERESPONSE_H
#define UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur10_robot_arm
{
template <class ContainerAllocator>
struct endEffectorPoseResponse_
{
  typedef endEffectorPoseResponse_<ContainerAllocator> Type;

  endEffectorPoseResponse_()
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)  {
    }
  endEffectorPoseResponse_(const ContainerAllocator& _alloc)
    : position_x(0.0)
    , position_y(0.0)
    , position_z(0.0)
    , orientation_x(0.0)
    , orientation_y(0.0)
    , orientation_z(0.0)
    , orientation_w(0.0)  {
  (void)_alloc;
    }



   typedef float _position_x_type;
  _position_x_type position_x;

   typedef float _position_y_type;
  _position_y_type position_y;

   typedef float _position_z_type;
  _position_z_type position_z;

   typedef float _orientation_x_type;
  _orientation_x_type orientation_x;

   typedef float _orientation_y_type;
  _orientation_y_type orientation_y;

   typedef float _orientation_z_type;
  _orientation_z_type orientation_z;

   typedef float _orientation_w_type;
  _orientation_w_type orientation_w;





  typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct endEffectorPoseResponse_

typedef ::ur10_robot_arm::endEffectorPoseResponse_<std::allocator<void> > endEffectorPoseResponse;

typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseResponse > endEffectorPoseResponsePtr;
typedef boost::shared_ptr< ::ur10_robot_arm::endEffectorPoseResponse const> endEffectorPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position_x == rhs.position_x &&
    lhs.position_y == rhs.position_y &&
    lhs.position_z == rhs.position_z &&
    lhs.orientation_x == rhs.orientation_x &&
    lhs.orientation_y == rhs.orientation_y &&
    lhs.orientation_z == rhs.orientation_z &&
    lhs.orientation_w == rhs.orientation_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_robot_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "401bc44765775bd133a9870625b1ac32";
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x401bc44765775bd1ULL;
  static const uint64_t static_value2 = 0x33a9870625b1ac32ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_robot_arm/endEffectorPoseResponse";
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position_x\n"
"float32 position_y\n"
"float32 position_z\n"
"float32 orientation_x\n"
"float32 orientation_y\n"
"float32 orientation_z\n"
"float32 orientation_w\n"
"\n"
;
  }

  static const char* value(const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position_x);
      stream.next(m.position_y);
      stream.next(m.position_z);
      stream.next(m.orientation_x);
      stream.next(m.orientation_y);
      stream.next(m.orientation_z);
      stream.next(m.orientation_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct endEffectorPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_robot_arm::endEffectorPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "position_x: ";
    Printer<float>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<float>::stream(s, indent + "  ", v.position_y);
    s << indent << "position_z: ";
    Printer<float>::stream(s, indent + "  ", v.position_z);
    s << indent << "orientation_x: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_x);
    s << indent << "orientation_y: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_y);
    s << indent << "orientation_z: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_z);
    s << indent << "orientation_w: ";
    Printer<float>::stream(s, indent + "  ", v.orientation_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_ROBOT_ARM_MESSAGE_ENDEFFECTORPOSERESPONSE_H
