// Generated by gencpp from file ur10_robot_arm/frameDevResponse.msg
// DO NOT EDIT!


#ifndef UR10_ROBOT_ARM_MESSAGE_FRAMEDEVRESPONSE_H
#define UR10_ROBOT_ARM_MESSAGE_FRAMEDEVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur10_robot_arm
{
template <class ContainerAllocator>
struct frameDevResponse_
{
  typedef frameDevResponse_<ContainerAllocator> Type;

  frameDevResponse_()
    : x_dev(0)
    , y_dev(0)  {
    }
  frameDevResponse_(const ContainerAllocator& _alloc)
    : x_dev(0)
    , y_dev(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_dev_type;
  _x_dev_type x_dev;

   typedef int32_t _y_dev_type;
  _y_dev_type y_dev;





  typedef boost::shared_ptr< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> const> ConstPtr;

}; // struct frameDevResponse_

typedef ::ur10_robot_arm::frameDevResponse_<std::allocator<void> > frameDevResponse;

typedef boost::shared_ptr< ::ur10_robot_arm::frameDevResponse > frameDevResponsePtr;
typedef boost::shared_ptr< ::ur10_robot_arm::frameDevResponse const> frameDevResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x_dev == rhs.x_dev &&
    lhs.y_dev == rhs.y_dev;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_robot_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e29eb4405f127a71471e9c031c76a1e5";
  }

  static const char* value(const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe29eb4405f127a71ULL;
  static const uint64_t static_value2 = 0x471e9c031c76a1e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_robot_arm/frameDevResponse";
  }

  static const char* value(const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 x_dev\n"
"int32 y_dev\n"
"\n"
;
  }

  static const char* value(const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_dev);
      stream.next(m.y_dev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct frameDevResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_robot_arm::frameDevResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_robot_arm::frameDevResponse_<ContainerAllocator>& v)
  {
    s << indent << "x_dev: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x_dev);
    s << indent << "y_dev: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y_dev);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_ROBOT_ARM_MESSAGE_FRAMEDEVRESPONSE_H
