// Generated by gencpp from file ur10_robot_arm/frameDevRequest.msg
// DO NOT EDIT!


#ifndef UR10_ROBOT_ARM_MESSAGE_FRAMEDEVREQUEST_H
#define UR10_ROBOT_ARM_MESSAGE_FRAMEDEVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur10_robot_arm
{
template <class ContainerAllocator>
struct frameDevRequest_
{
  typedef frameDevRequest_<ContainerAllocator> Type;

  frameDevRequest_()
    : color()  {
    }
  frameDevRequest_(const ContainerAllocator& _alloc)
    : color(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;





  typedef boost::shared_ptr< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> const> ConstPtr;

}; // struct frameDevRequest_

typedef ::ur10_robot_arm::frameDevRequest_<std::allocator<void> > frameDevRequest;

typedef boost::shared_ptr< ::ur10_robot_arm::frameDevRequest > frameDevRequestPtr;
typedef boost::shared_ptr< ::ur10_robot_arm::frameDevRequest const> frameDevRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator1> & lhs, const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ur10_robot_arm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89e44dcab627a2c43a70ae1100695caa";
  }

  static const char* value(const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89e44dcab627a2c4ULL;
  static const uint64_t static_value2 = 0x3a70ae1100695caaULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_robot_arm/frameDevRequest";
  }

  static const char* value(const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color\n"
"\n"
;
  }

  static const char* value(const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct frameDevRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_robot_arm::frameDevRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_robot_arm::frameDevRequest_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_ROBOT_ARM_MESSAGE_FRAMEDEVREQUEST_H
